name: Java CI with Maven

on:
  push:
    paths:
      - 'locations-service/**'
      - 'mvalues/**'
      - 'reporting-service/**'
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file locations-service/pom.xml
    - name: Build with Maven for mvalues 
      run: mvn -B package --file mvalues/pom.xml
    - name: Build with Maven for reporting-service
      run: mvn -B package --file reporting-service/pom.xml
